"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Kevan Hollbach"
email = "khollbach@gmail.com"

[ui]
default-command = "log"
movement.edit = true
diff-formatter = ":git"
pager = "delta --pager less"
